#pragma once
#include "../DonutCore/DonutCorePch.h"
#include "../DonutEngine/DonutEnginePch.h"
#include "../DonutShaders/DonutShadersPch.h"

#include "../nvrhi/nvrhi.h"

#include "../DonutRender/BloomPass.h"
#include "../DonutRender/CascadedShadowMap.h"
#include "../DonutRender/DeferredLightingPass.h"
#include "../DonutRender/DepthPass.h"
#include "../DonutRender/DrawStrategy.h"
#include "../DonutRender/EnvironmentMapPass.h"
#include "../DonutRender/ForwardShadingPass.h"
#include "../DonutRender/GBuffer.h"
#include "../DonutRender/GBufferFillPass.h"
#include "../DonutRender/GeometryPasses.h"
#include "../DonutRender/JointsRenderPass.h"
#include "../DonutRender/LightProbeProcessingPass.h"
#include "../DonutRender/MipMapGenPass.h"
#include "../DonutRender/PixelReadbackPass.h"
#include "../DonutRender/PlanarShadowMap.h"
#include "../DonutRender/SkyPass.h"
#include "../DonutRender/SsaoPass.h"
#include "../DonutRender/TemporalAntiAliasingPass.h"
#include "../DonutRender/ToneMappingPasses.h"